CREATE TABLE Usuario(
correo VARCHAR(40) NOT NULL PRIMARY KEY,
activo BOOLEAN DEFAULT TRUE,
nombreUsuario VARCHAR(50) NOT NULL,
rol INT NOT NULL,
contrasenia VARCHAR(60) NOT NULL
);

CREATE TABLE Tema(
idTema SERIAL NOT NULL PRIMARY KEY,
nombreTema VARCHAR(60) NOT NULL,
r  INT NOT NULL ,
g INT NOT NULL,
b INT NOT NULL,
correo VARCHAR(40) NOT NULL,
FOREIGN KEY (correo) REFERENCES Usuario(correo) ON UPDATE CASCADE
);

CREATE TABLE Marcador(
idMarcador SERIAL NOT NULL PRIMARY KEY,
descripcion VARCHAR(100) NOT NULL,
latitud DOUBLE PRECISION NOT NULL,
longitud DOUBLE PRECISION NOT NULL,
idTema INTEGER NOT NULL,
FOREIGN KEY (idTema) REFERENCES Tema(idTema)
);

CREATE TABLE Comentario(
idComentario SERIAL NOT NULL PRIMARY KEY,
calificacion INT,
descripcion VARCHAR(100) NOT NULL,
correo  VARCHAR(40) NOT NULL,
idMarcador INTEGER NOT NULL,
FOREIGN KEY (correo) REFERENCES Usuario(correo) ON UPDATE CASCADE,
FOREIGN KEY (idMarcador) REFERENCES Marcador(idMarcador) ON UPDATE CASCADE on DELETE CASCADE
);

CREATE TABLE MeGusta(
idMeGusta SERIAL NOT NULL PRIMARY KEY,
valor BIT(1),
correo VARCHAR(40) NOT NULL,
idcomentario INT NOT NULL,
FOREIGN KEY (correo) REFERENCES Usuario(correo) ON UPDATE CASCADE,
FOREIGN KEY (idcomentario) REFERENCES Comentario(idcomentario) ON UPDATE CASCADE
);

