package com.mycompany.luamaps.modelo;
// Generated 31/03/2019 03:36:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int idcomentario;
     private Marcador marcador;
     private Usuario usuario;
     private Integer calificacion;
     private String descripcion;
     private Set megustas = new HashSet(0);

    public Comentario() {
    }
    
    public Comentario(int idcomentario, Marcador marcador, Usuario usuario, String descripcion) {
        this.idcomentario = idcomentario;
        this.marcador = marcador;
        this.usuario = usuario;
        this.descripcion = descripcion;
        this.calificacion = 0;
    }
    public Comentario(int idcomentario, Marcador marcador, Usuario usuario, Integer calificacion, String descripcion, Set megustas) {
       this.idcomentario = idcomentario;
       this.marcador = marcador;
       this.usuario = usuario;
       this.calificacion = calificacion;
       this.descripcion = descripcion;
       this.megustas = megustas;
    }
   
    public int getIdcomentario() {
        return this.idcomentario;
    }
    
    public void setIdcomentario(int idcomentario) {
        this.idcomentario = idcomentario;
    }
    public Marcador getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(Marcador marcador) {
        this.marcador = marcador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getMegustas() {
        return this.megustas;
    }
    
    public void setMegustas(Set megustas) {
        this.megustas = megustas;
    }
}


