package com.mycompany.luamaps.modelo;
// Generated 31/03/2019 03:36:41 PM by Hibernate Tools 4.3.1

import com.mycompany.luamaps.modelo.Comentario;




/**
 * Megusta generated by hbm2java
 */
public class Megusta  implements java.io.Serializable {


     private int idmegusta;
     private Comentario comentario;
     private Usuario usuario;
     private Boolean valor;

    public Megusta() {
    }

	
    public Megusta(int idmegusta, Comentario comentario, Usuario usuario) {
        this.idmegusta = idmegusta;
        this.comentario = comentario;
        this.usuario = usuario;
    }
    public Megusta(int idmegusta, Comentario comentario, Usuario usuario, Boolean valor) {
       this.idmegusta = idmegusta;
       this.comentario = comentario;
       this.usuario = usuario;
       this.valor = valor;
    }
   
    public int getIdmegusta() {
        return this.idmegusta;
    }
    
    public void setIdmegusta(int idmegusta) {
        this.idmegusta = idmegusta;
    }
    public Comentario getComentario() {
        return this.comentario;
    }
    
    public void setComentario(Comentario comentario) {
        this.comentario = comentario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Boolean getValor() {
        return this.valor;
    }
    
    public void setValor(Boolean valor) {
        this.valor = valor;
    }




}


