package com.mycompany.luamaps.modelo;
// Generated 31/03/2019 03:36:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private int idtema;
     private Usuario usuario;
     private String nombretema;
     private String color;
     private Set marcadors = new HashSet(0);

    public Tema() {
    }

	
    public Tema(int idtema, Usuario usuario, String nombretema, String color) {
        this.idtema = idtema;
        this.usuario = usuario;
        this.nombretema = nombretema;
        this.color = color;
    }
    public Tema(int idtema, Usuario usuario, String nombretema, String color, Set marcadors) {
       this.idtema = idtema;
       this.usuario = usuario;
       this.nombretema = nombretema;
       this.color = color;
       this.marcadors = marcadors;
    }
   
    public int getIdtema() {
        return this.idtema;
    }
    
    public void setIdtema(int idtema) {
        this.idtema = idtema;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombretema() {
        return this.nombretema;
    }
    
    public void setNombretema(String nombretema) {
        this.nombretema = nombretema;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }
    
    public void addMarcador (Marcador m) {
        marcadors.add(m);
    }




}


