package com.mycompany.luamaps.modelo;
// Generated 31/03/2019 03:36:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String correo;
     private Boolean activo;
     private String nombreusuario;
     private int rol;
     private String contrasenia;
     private Set temas = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set megustas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String correo, String nombreusuario, int rol, String contrasenia) {
        this.correo = correo;
        this.nombreusuario = nombreusuario;
        this.rol = rol;
        this.contrasenia = contrasenia;
    }
    public Usuario(String correo, Boolean activo, String nombreusuario, int rol, String contrasenia, Set temas, Set comentarios, Set megustas) {
       this.correo = correo;
       this.activo = activo;
       this.nombreusuario = nombreusuario;
       this.rol = rol;
       this.contrasenia = contrasenia;
       this.temas = temas;
       this.comentarios = comentarios;
       this.megustas = megustas;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public int getRol() {
        return this.rol;
    }
    
    public void setRol(int rol) {
        this.rol = rol;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getMegustas() {
        return this.megustas;
    }
    
    public void setMegustas(Set megustas) {
        this.megustas = megustas;
    }




}


